docker and its dependences

diff --git a/users/Dockerfile b/users/Dockerfile
--- a/users/Dockerfile
+++ b/users/Dockerfile
@@ -1,18 +1,55 @@
-FROM debian:jessie
-MAINTAINER Jean-Avit Promis "docker@katagena.com"
-LABEL org.label-schema.vcs-url="https://github.com/nouchka/docker-sqlite3"
-LABEL version="latest"
+FROM php:7.2-fpm
+#### must start exactly:   FROM bla:bla
 
-RUN apt-get update && \
-	DEBIAN_FRONTEND=noninteractive apt-get -yq install sqlite3 && \
-	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
+ENV PHP_VER=7.2 \
+    PHALCON_VERSION=3.4.4 \
+    PHALCON_EXT_PATH=php7/64bits \
+    TZ=Asia/Bishkek
 
-RUN mkdir -p /tmp/db
+RUN apt update && apt install -y \
+#    && docker-php-ext-install opcache \
+    curl \
+    zip
 
-WORKDIR /tmp/db
-ENTRYPOINT [ "sqlite3" ]
+# APCu
+#RUN pecl install -y apcu-5.1.8
+#    && docker-php-ext-enable apcu
+#RUN echo "extension=apcu.so" > /usr/local/etc/php/conf.d/apcu.ini
 
-ADD ngnix_php.sh /usr/bin/ngnix_php.sh
-RUN chmod a+x /usr/bin/ngnix_php.sh
+# ext-apcu
+RUN mkdir -p /usr/src/php/ext/apcu \
+    && curl -fsSL https://github.com/krakjoe/apcu/archive/v5.1.8.tar.gz | tar xvz -C /usr/src/php/ext/apcu --strip 1 \
+    && docker-php-ext-install apcu \
+    # ext-bcmath, ext-sockets
+    && docker-php-ext-install bcmath sockets \
+    ## cleanup
+    && docker-php-source delete
 
-ENTRYPOINT [ "ngnix_php.sh" ]
+# Phalcon install
+RUN set -xe && \
+        cd /tmp && \
+        # Compile Phalcon
+        curl -LO https://github.com/phalcon/cphalcon/archive/v${PHALCON_VERSION}.tar.gz && \
+        tar xzf /tmp/v${PHALCON_VERSION}.tar.gz && \
+        docker-php-ext-install -j $(getconf _NPROCESSORS_ONLN) /tmp/cphalcon-${PHALCON_VERSION}/build/${PHALCON_EXT_PATH} && \
+        # Remove all temp files
+        rm -r \
+            /tmp/v${PHALCON_VERSION}.tar.gz \
+            /tmp/cphalcon-${PHALCON_VERSION}
+
+# Timezone
+RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
+
+# Composer
+RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
+
+#RUN service php${PHP_VER}-fpm-sp restart
+
+# Default stuff
+ADD run.sh /run.sh
+
+RUN chmod 755 /run.sh
+
+WORKDIR "/var/www/html"
+
+CMD ["/run.sh"]
